### ISSUE TITLE
vite 打包后找不到模型文件

### ISSUE THREAD

**Issue by YAANLE** [Mingo-233/vite-threejs-template#1]
![image](https://user-images.githubusercontent.com/35681169/230858387-d53e1198-145e-4bcd-a04c-d51adc4a18a9.png)
![image](https://user-images.githubusercontent.com/35681169/230859236-bc070116-005b-4990-a274-eecc065f1e35.png)

**Comment by YAANLE** [comment]
我自己的项目也是一样，开发环境没问题 ，打包之后就一直找不到模型文件， 请问有没有什么好的解决办法

**Comment by Mingo-233** [comment]
> 我自己的项目也是一样，开发环境没问题 ，打包之后就一直找不到模型文件， 请问有没有什么好的解决办法

build和build:one都没有复现类似问题，打包后的产物需要运行在一个服务上，可以试试执行pnpm preview。vite会本地起个node服务

**Comment by YAANLE** [comment]
已经查到原因,我项目的资源文件没放到public目录下。。。感谢
